### ISSUE TITLE
AttributeError: module 'general_purpose.utilities' has no attribute 'keys_exists'

### ISSUE THREAD

**Issue by georgemilosh** [AlessandroLovo/general_purpose#9]
I've noticed this today while running an old script of Climate-Learning:
```
==Reading data==
Traceback (most recent call last):
  File "/mnt/homedafs-2.10/gmiloshe/Climate-Learning/VAE/analogue_george.py", line 167, in <module>
    if (ut.keys_exists(run_vae_kwargs, 'label_period_start') and ut.keys_exists(run_vae_kwargs, 'label_period_end')):
AttributeError: module 'general_purpose.utilities' has no attribute 'keys_exists'
```
Did you change something?

**Comment by georgemilosh** [comment]
No I think it is something else...

**Comment by AlessandroLovo** [comment]
There were breaking changes in the fix of #6. For the matter at hand, `keys_exists` was renamed to `key_exists`

**Comment by AlessandroLovo** [comment]
yes, I'll do it stat

**Comment by AlessandroLovo** [comment]
Please read the other breaking changes that were introduced for #6 and tell me if they make problems for you

**Comment by AlessandroLovo** [comment]
I added back the `keys_exists` method. But if you can, I recommend rather doing replace all in the files involved.
The name of the function was misleading, as it checks only one key, so I'd rather not stick around with it too much
